/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i interface_adaptor.h -a :interface_adaptor.cpp ../AppSetup/com.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "interface_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AppEngineAdaptor
 */

AppEngineAdaptor::AppEngineAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AppEngineAdaptor::~AppEngineAdaptor()
{
    // destructor
}

int AppEngineAdaptor::hideWindow(int appID)
{
    // handle method call local.AppEngine.hideWindow
    int out0;
    QMetaObject::invokeMethod(parent(), "hideWindow", Q_RETURN_ARG(int, out0), Q_ARG(int, appID));
    return out0;
}

void AppEngineAdaptor::requestShow(int appID)
{
    // handle method call local.AppEngine.requestShow
    QMetaObject::invokeMethod(parent(), "requestShow", Q_ARG(int, appID));
}

int AppEngineAdaptor::showWindow(int appID)
{
    // handle method call local.AppEngine.showWindow
    int out0;
    QMetaObject::invokeMethod(parent(), "showWindow", Q_RETURN_ARG(int, out0), Q_ARG(int, appID));
    return out0;
}

