/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i appmain_adaptor.h -a :appmain_adaptor.cpp ../AppMain/local.AppMain.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "appmain_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AppMainAdaptor
 */

AppMainAdaptor::AppMainAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AppMainAdaptor::~AppMainAdaptor()
{
    // destructor
}

void AppMainAdaptor::deregistrationAppID(int appid, const QString &appname)
{
    // handle method call local.AppMain.deregistrationAppID
    QMetaObject::invokeMethod(parent(), "deregistrationAppID", Q_ARG(int, appid), Q_ARG(QString, appname));
}

void AppMainAdaptor::registrationAppID(int appid, const QString &appname, const QString &servicename, const QString &objectpath)
{
    // handle method call local.AppMain.registrationAppID
    QMetaObject::invokeMethod(parent(), "registrationAppID", Q_ARG(int, appid), Q_ARG(QString, appname), Q_ARG(QString, servicename), Q_ARG(QString, objectpath));
}

void AppMainAdaptor::requestShow(int appid)
{
    // handle method call local.AppMain.requestShow
    QMetaObject::invokeMethod(parent(), "requestShow", Q_ARG(int, appid));
}

