/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a interface_adaptor.h: ../AppHomeScreen/com.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef INTERFACE_ADAPTOR_H
#define INTERFACE_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.AppEngine
 */
class AppEngineAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.AppEngine")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.AppEngine\">\n"
"    <method name=\"showWindow\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"appID\"/>\n"
"    </method>\n"
"    <method name=\"hideWindow\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"appID\"/>\n"
"    </method>\n"
"    <method name=\"requestShow\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"appID\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AppEngineAdaptor(QObject *parent);
    virtual ~AppEngineAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int hideWindow(int appID);
    void requestShow(int appID);
    int showWindow(int appID);
Q_SIGNALS: // SIGNALS
};

#endif
